'''Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

Explanation : 

Step 1: Iterate over the entire String
Step 2: Iterate from the end of string 
        in order to generate different substring
        add the subtring to the list
Step 3: Drop kth character from the substring obtained 
        from above to generate different subsequence.
Step 4: if the subsequence is not in the list then recur.'''


final = []
def subsequence(s):
    for i in range(len(s)):
        for j in range(len(s), i, -1):
            substr = s[i:j]
            if (substr not in final):
                final.append(substr)
            for k in range(1, len(substr)-1):
                subs = substr
                substring = subs[:k] + subs[k+1:]
                if substring not in final:
                    subsequence(substring)
                
                
s = str(input())

subsequence(s)

final_sorted = sorted(final, key = len)
print(*final_sorted)
